#!/usr/bin/env bash

set -e
#echo ''

DOTFILES_ROOT="${HOME}/.dotfilez"
DOTFILES_REPO="git@github.com:rrichardsonv/dotfilez.git"

#if [[ ! -d ${DOTFILES_ROOT} ]]; then
#  echo "Cloning repo"
#  git clone ${DOTFILES_REPO} ${DOTFILES_ROOT}
#fi

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

# For manual installation
"./${DOTBOT_DIR}/${DOTBOT_BIN}" -d . -c "${CONFIG}" "${@}"

# Default installation
#"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
